/*
 * generated by Xtext 2.25.0
 */
package org.xtext.projet1.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import projetHTML.ui.internal.ProjetHTMLActivator;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ProjetHTMLActivator.getInstance().getInjector("org.xtext.projet1.MyDsl");
	}

}
