/*
 * generated by Xtext 2.25.0
 */
package org.xtext.projet1.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import projetHTML.ui.internal.ProjetHTMLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ProjetHTMLActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ProjetHTMLActivator activator = ProjetHTMLActivator.getInstance();
		return activator != null ? activator.getInjector(ProjetHTMLActivator.ORG_XTEXT_PROJET1_MYDSL) : null;
	}

}
