/*
 * generated by Xtext 2.25.0
 */
package org.xtext.projet1;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
