NameDashboard : "Pourcentage dInegalité par pays (sparse data)(Comparaison de 3 types de graph)"

CSV : '/Users/lenaoudjman/Desktop/ProjetDsl/Senar5/gini2.csv'
Delimiter : ";"
TypeOfGraph : Line
Abscissa : "GINI index"
Ordinate(s) : "Estonia" "Thailand" "Ghana" 
TitleAxeX : "Date"
TitleAxeY : "Pourcentage dinegalité"
Color(s) graph : "green" "blue" "red"


CSV : '/Users/lenaoudjman/Desktop/ProjetDsl/Senar5/gini2.csv'
Delimiter : ";"
TypeOfGraph : Nuage de point
Abscissa : "GINI index"
Ordinate(s) : "Estonia" "Thailand" "Ghana" 
TitleAxeX : "Date"
TitleAxeY : "Pourcentage dinegalité"
Color(s) graph : "green" "blue" "red"



CSV : '/Users/lenaoudjman/Desktop/ProjetDsl/Senar5/gini2.csv'
Delimiter : ";"
TypeOfGraph : Bar
Abscissa : "GINI index"
Ordinate(s) : "Estonia" "Thailand" "Ghana" 
TitleAxeX : "Date"
TitleAxeY : "Pourcentage dinegalité"
Color(s) graph : "green" "blue" "red"